export const positionTableColumns = [
    { key: 'symbol', label: 'Symbol' },
    { key: 'ticket', label: 'Ticket' },
    { key: 'time', label: 'Time' },
    { key: 'type', label: 'Type' },
    { key: 'volume', label: 'Volume' },
    { key: 'entry_price', label: 'Entry Price' },
    { key: 'sl', label: 'SL' },
    { key: 'tp', label: 'TP' },
    { key: 'current_price', label: 'Current Price' },
    { key: 'profit', label: 'Profit' },
    { key: 'actions', label: 'Actions' },
    {
        key: 'show_details',
        label: '',
        _style: { width: '1%' },
        filter: false,
        sorter: false,
    },
];
